### PR TITLE
Add copy title option in right click dropdown

### PR DESCRIPTION
**Pull request by ohuang12**
Addresses issue [#210](https://github.com/koppor/jabref/issues/210) from [@koppor](https://github.com/koppor).

Adds an option to copy the title of a bibtex entry when right clicking one (or more) to the clipboard.
Also adds the option to copy the title using `Edit -> Copy title`.

edit_menu
right_click_menu

- [x] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [x] Screenshots added (for bigger UI changes)
- [x] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [x] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by RolfStarre** [comment]
Are there more empty variables in the localization file?

Like your `Copy_title=`

**Comment by ohuang12** [comment]
Yes many, many, many more...
The Dutch localization is also quite empty 😄

**Comment by RolfStarre** [comment]
Ok, looks good to me then

**Comment by ohuang12** [comment]
I'm currently still resolving some issues with the localizations (two localization tests are currently failing).

**Comment by RolfStarre** [comment]
Ah, then it looks bad to me 😝 

Did you manually test the changed features in running JabRef? 😛

**Comment by ohuang12** [comment]
Yes it is tested manually, I've been able to fix the issue with the localization tests.
Several strings were not set inside the localization (and also a small error in using the wrong localization file for menu items 😄 )

**Comment by RolfStarre** [comment]
👍

**Review by RolfStarre — APPROVED** [review]
LGTM

**Pull request closed without merging**
